---
authors:
  - "Gaudenz Steinlin <gaudenz.steinlin@cloudscale.ch>"
  - "Denis Krienbühl <denis.krienbuehl@cloudscale.ch>"
  - "René Moser <mail@renemoser.net>"
dependencies: {}
description: 'Ansible Collection for cloudscale.ch'
documentation: ''
homepage: 'https://github.com/ngine-io/ansible-collection-cloudscale'
issues: 'https://github.com/ngine-io/ansible-collection-cloudscale/issues'
license: GPL-3.0-or-later
name: cloudscale
namespace: ngine_io
readme: README.md
repository: 'https://github.com/ngine-io/ansible-collection-cloudscale'
tags:
  - cloud
  - cloudscale
  - ngine_io
version: 1.0.1
