name: Collection integration

on:
  push:
  pull_request:
  # schedule:
  # - cron: 3 0 * * *  # Run daily at 0:03 UTC

jobs:
  build-collection-artifact:
    name: Build collection
    runs-on: ${{ matrix.runner-os }}
    strategy:
      matrix:
        runner-os:
        - ubuntu-latest
        ansible-version:
        - git+https://github.com/ansible/ansible.git@devel
        # - git+https://github.com/ansible/ansible.git@stable-2.9
        # - ansible
        runner-python-version:
        - 3.8
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.runner-python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.runner-python-version }}
    - name: Install Ansible ${{ matrix.ansible-version }}
      run: |
        python -m pip install --upgrade pip
        pip install ${{ matrix.ansible-version }}
        pip install -r test-requirements.txt
    - name: Build a collection tarball
      run: |
        ansible-galaxy collection build .
        ansible-galaxy collection install *.gz
    - name: Add service account file
      env:
        CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
      run: |
        pushd ~/.ansible/collections/ansible_collections/cloudscale_ch/cloud
        echo "$CONFIG_FILE" > tests/integration/cloud-config-cloudscale.ini
    - name: Run the tests
      run: |
        pushd ~/.ansible/collections/ansible_collections/cloudscale_ch/cloud
        ansible-test integration -v --allow-unsupported --continue-on-error cloud/cloudscale/
