name: Mail info test

on:
  schedule:
  - cron: '*/5 * * * *'  # Run all 5 minutes

jobs:
  integration-test:
    name: Integration test using Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner-python-version:
        - 3.6
        python-version:
        - 3.6
        - 2.7
    steps:
      - name: Dump GitHub context
        id: github_context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # - name: Fail this
      #   id: failing
      #   run: '/bin/false'
      - name: Don't fail this
        id: succeeding
        run: '/bin/true'
      - name: Dump steps context
        id: steps_context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Send mail in case of failure
        id: send_mail
        if: ${{ failure() }}
        shell: python3 {0}
        run: |
          from smtplib import SMTP
          from email.message import EmailMessage

          email = EmailMessage()
          email['TO'] = '${{ secrets.CRON_RCPT }}'
          email['FROM'] = 'noreply@github.com'
          email['Subject'] = 'Ansible Cloud Module Integration Test Failure'
          email.set_content("""
          Integration tests using Python ${{ matrix.python-version }} failed:
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          """)

          with SMTP('${{ secrets.MAILSERVER }}') as smtp:
            smtp.starttls()
            smtp.send_message(email)
